name: Release by VERSION.txt

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main
    paths:
      - VERSION.txt
      - CHANGELOG

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from VERSION.txt
        id: version
        run: |
          VERSION=$(cat VERSION.txt | tr -d ' \n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          if git rev-parse ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists. Skip."
            exit 0
          fi

      - name: Extract release notes and date from CHANGELOG
        id: changelog
        run: |
          VERSION=${{ env.VERSION }}

          # 检查 CHANGELOG 中是否有对应版本标题
          HEADER=$(grep "^## \\[$VERSION\\]" CHANGELOG || true)
          if [ -z "$HEADER" ]; then
            echo "❌ ERROR: CHANGELOG 中没有找到 $VERSION 对应的版本说明"
            exit 1
          fi

          # 从标题中提取日期（格式: YYYY-MM-DD）
          DATE=$(echo "$HEADER" | sed -E 's/.*- ([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\1/')
          echo "RELEASE_DATE=$DATE" >> $GITHUB_ENV

          # 提取对应版本的内容
          awk "/^## \\[$VERSION\\]/ {flag=1; next} /^## \\[/ {flag=0} flag {print}" CHANGELOG > RELEASE_BODY.md

          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat RELEASE_BODY.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }} (${{ env.RELEASE_DATE }})"
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
