name: Release by VERSION.txt

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main           # 仅 main 分支
    paths:
      - VERSION.txt
      - CHANGELOG      # CHANGELOG 改动时也触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from VERSION.txt
        id: version
        run: |
          VERSION=$(cat VERSION.txt | tr -d ' \n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          if git rev-parse ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists. Skip."
            exit 0
          fi

      - name: Extract release notes from CHANGELOG
        id: changelog
        run: |
          VERSION=${{ env.VERSION }}
          awk "/^## \\[$VERSION\\]/ {flag=1; next} /^## \\[/ {flag=0} flag {print}" CHANGELOG > RELEASE_BODY.md

          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          cat RELEASE_BODY.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: ${{ env.RELEASE_BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
