name: Auto Tag and Release

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main           # 监听 main 分支

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create new tag
        run: |
          VERSION="v1.0.$(date +'%Y%m%d%H%M')"   # 根据时间自动生成版本号
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag $VERSION
          git push origin $VERSION

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "这是自动生成的发行版"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
