name: Release by VERSION.txt

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main           # main 分支更新时触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from VERSION.txt
        id: version
        run: |
          VERSION=$(cat VERSION.txt | tr -d ' \n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          if git rev-parse ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists. Skip."
            exit 0
          fi

      - name: Create new tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION=${{ env.VERSION }}

          # 提取 CHANGELOG 中对应版本的内容
          # 例如 VERSION=4.3.5，则匹配 "## [4.3.5]" 开头的段落
          CHANGELOG=$(awk "/^## \\[$VERSION\\]/{flag=1;next}/^## \\[/{flag=0}flag" CHANGELOG | sed '/^$/d')

          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="⚠️ 未找到 $VERSION 的更新记录，请检查 CHANGELOG 文件。"
          fi

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "body=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: ${{ steps.changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
