name: Sync Upstream Branches

on:
  schedule:
    - cron: "0 2 * * *"   # 每天凌晨 2 点执行一次
  workflow_dispatch:        # 也支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 必须完整拉取，避免丢历史

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/SzeMeng76/LunaTV.git
          git fetch upstream

      - name: Sync branches
        run: |
          # 遍历上游所有分支，并强制同步到 fork
          for branch in $(git branch -r | grep upstream/ | sed 's|upstream/||'); do
            echo "Syncing branch: $branch"
            git checkout -B $branch upstream/$branch
            git push origin $branch --force
          done
